# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c593e27fd85d512427eff6494dd7a89bb7fd4deca17eb726de21164b5b39a235af21f62396e03f9be2f3deb1de68ae4a7be07656a72444ff7c08607e0a144283

test:
  secret_key_base: d44160105a0ecca4cbd136d05fc647af97a6842dff9073c487b649a8be4e39c86c8dd7751902de45f3b386e41019b80c0d716372882fee542c987ce4d6cda27a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
